"""add_date_use

Revision ID: 43e103cd1d08
Revises: c1ecb62ca276
Create Date: 2025-03-23 13:17:40.289339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e103cd1d08'
down_revision: Union[str, None] = 'c1ecb62ca276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('number_of_click', sa.Integer(), nullable=True))
    op.add_column('links', sa.Column('creation_date', sa.DateTime(), server_default='now()', nullable=True))
    op.add_column('links', sa.Column('date_use', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'date_use')
    op.drop_column('links', 'creation_date')
    op.drop_column('links', 'number_of_click')
    # ### end Alembic commands ###
